### PR TITLE
fix: formatting of empty tags with prop spreading (#151)

### LINKED ISSUE #151: Empty tag with properties doesn't compile after formatting
Leptosfmt removes necessary formatting for prop spreading (new in Leptos 0.7).
When trying to format `<{..} class="a" />` it removes the `..`, formatting as `<{} class="a" />` and the file doesn't compile anymore:

```rust
let form_control = view! { <{..} class="form-control" /> };
let size_class = view! { <{..} class="w-40" /> };

view! {
    <label {..form_control.clone()} {..size_class.clone()}>
    </label>
}
```
becomes 
```rust
let form_control = view! { <{} class="form-control" /> };
let size_class = view! { <{} class="w-40" /> };

view! {
    <label {..form_control.clone()} {..size_class.clone()}>
    </label>
}
```

```
error: expected identifier, found `{`
 --> file.rs:5:33
  |
5 |     let form_control = view! { <{} class="form-control" /> };
  |                                 ^^ expected identifier
  ```

See also https://github.com/leptos-rs/leptos/blob/eba08ad5927478b1d600959abb5513119bccdb26/examples/spread/src/lib.rs for some examples of prop spreading using empty tags.

### PR DESCRIPTION
**Pull request by osmano807**
This commit addresses the issue where leptosfmt incorrectly removed the '..' from empty tags with prop spreading, causing compilation errors. The formatter now correctly preserves the '..' in expressions like `<{..} class="foo" />.`

Fixes #151

### CODE REVIEW

File: formatter/src/formatter/node.rs [hunk 1]
```diff
@@ -51,7 +51,34 @@ impl Formatter<'_> {
...
+                            self.printer.word("{..}");
+                            return;
+                        }
+                    }
+                }
+
+                // Default handling if it doesn't match any specific pattern
+                self.printer.word(name.to_string())
+            }
+        }
```
Comment (bram209) [inline formatter/src/formatter/node.rs:81]: There is already a formatter method that formats node value blocks ;)

```suggestion
        if let NodeName::Block(block) = name {
            self.node_value_block_expr(block, false, false);
        } else {
            self.printer.word(name.to_string());
        }
```

File: formatter/src/formatter/node.rs [hunk 2]
```diff
@@ -51,7 +51,34 @@ impl Formatter<'_> {
...
     }
```
Comment (bram209) [inline formatter/src/formatter/node.rs:82]: Unrelated to your change, but could you add these to `attribute.rs` for completeness?

```rust
    #[test]
    fn prop_spreading_unnamed() {
        let f = format_attribute! {  {..}  };
        assert_snapshot!(f, @r#"{..}"#)
    }

    #[test]
    fn prop_spreading_named() {
        let f = format_attribute! {  { ..some_props }  };
        assert_snapshot!(f, @r#"{..some_props}"#)
    }
```

**Review by bram209 — APPROVED** [review]

**Review by bram209 — CHANGES_REQUESTED** [review]
Overall looks good, added a suggestion to use the pre-existing way for formatting node value block expressions. Thank you for your contribution!

File: formatter/src/formatter/node.rs (hunk 1 above)
Comment (osmano807) [reply formatter/src/formatter/node.rs]: Good, I was sure I missed something better.

**Comment by osmano807** [comment]
I pushed a new revision with the suggested changes, thanks for looking at it

**Review by bram209 — APPROVED** [review]

**Comment by bram209** [comment]
thanks!
